config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get 'home/about'
  get 'search' => 'search#search'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  		get 'follows' => 'relationships#follower', as: 'follows'
      get 'followers' => 'relationships#followed', as: 'followers'
  end

   resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
   	resource :favorites, only: [:create, :destroy]
     resource :book_comments, only: [:create, :destroy]
   end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :book_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	 before_action :authenticate_user!
  before_action :set_book

  def create
    @book.favorites.create(user_id: current_user.id)
  end

  def destroy
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :book_id)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_button.html.erb
<% if book.favorited_by?(current_user) %>

  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="glyphicon glyphicon-heart"></i>
  <% end %>

<% else %>

  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="glyphicon glyphicon-heart-empty"></i>
  <% end %>

<% end %>

<%= book.favorites.count %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %>").html("<%= j(render 'books/item', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %>").html("<%= j(render 'books/item', book: @book) %>");