config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get 'home/about'
  get 'search' => 'search#search'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  		get 'follows' => 'relationships#follower', as: 'follows'
      get 'followers' => 'relationships#followed', as: 'followers'
  end

   resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
   	resource :favorites, only: [:create, :destroy]
     resource :book_comments, only: [:create, :destroy]
   end

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where(title: "#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
#before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def show
    @book = Book.find(params[:id])
    @bookpost = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    @favorite = Favorite.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @favorite = Favorite.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
        if current_user.id != @book.user_id
           redirect_to books_path
        end
  end



  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

 # def ensure_correct_user
  #    @book = Book.find(params[:id])
   # unless @book.user == current_user
    #   redirect_to books_path
     #end
   #end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<% book_comments.each do |book_comment| %>
     <div class="comment">
            <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
            <%= book_comment.user.name %>
            <%= book_comment.comment %>
             <!-- 削除機能-->
         <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comments_path(book_id: book_comment.book, book_comment_id: book_comment), method: :delete, remote: true, class: "btn-sm btn-danger" %>
         <% end %>
    </div>
<% end %>

app/views/books/_item.html.erb
<td>
	<%= link_to user_path(book.user) do %>
		<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
	<% end %>
</td>

<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>

<td><%= book.body %></td>

<td>
	<%= render 'favorites/favorite_button', book: book %>
</td>

<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_list.html.erb
<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% books.each do |book| %>
				<tr id ="book_<%= book.id %>">
					<%= render 'books/item', book: book %>
				</tr>
			<% end %>
	    </tbody>
</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
    <% if book.errors.any? %>
		<div id="error_explanation">
			<h3><%= book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<%= render 'books/list', books: @books %>
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @bookpost %>

	</div>

    <div class="col-xs-9">
		   <h2>Book detail</h2>

		    <table class="table">
				<tr id="book_<%= @book.id %>">
					<%= render 'books/item', book: @book %>
					<% if @book.user_id == current_user.id %>
		                 <td class="edit_book"><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>
		                 </td>
		                 <td class="destroy_book"><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
		                 </td>
		            <% end %>
				</tr>
			</table>
		<div id="comments_index">
			<%= render 'comment', book_comments: @book_comments %>
		</div>
		<div id="comment_area">
			<%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
		</div>
    </div>
</div>