config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  get 'home/about'
  get 'search' => 'search#search'

  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  		get 'follows' => 'relationships#follower', as: 'follows'
      get 'followers' => 'relationships#followed', as: 'followers'
  end

   resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
   	resource :favorites, only: [:create, :destroy]
     resource :book_comments, only: [:create, :destroy]
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where(title: "#{word}")
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
    belongs_to :book
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  has_many :follower, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followed, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  attachment :profile_image, destroy: false

  #geocoded_by :address
  #after_validation :geocode, if: :address_changed?

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :city, presence: true
  validates :street, presence: true


  #ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  #ユーザーのフォローを解除する
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  #すでにフォロー済みであればture返す
  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
        if    search == "perfect_match"
                        @user = User.where(name: "#{word}")
        elsif search == "backward_match"
                        @user = User.where("name LIKE?","%#{word}")
        elsif search == "forward_match"
                        @user = User.where("name LIKE?","#{word}%")
        elsif search == "partial_match"
                        @user = User.where("name LIKE?","%#{word}%")
        else
                        @user = User.all
        end
  end

  include JpPrefecture
  jp_prefecture :prefect_code

  def prefectture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
#before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def show
    @book = Book.find(params[:id])
    @bookpost = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
    @favorite = Favorite.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @favorite = Favorite.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
        if current_user.id != @book.user_id
           redirect_to books_path
        end
  end



  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

 # def ensure_correct_user
  #    @book = Book.find(params[:id])
   # unless @book.user == current_user
    #   redirect_to books_path
     #end
   #end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	 before_action :authenticate_user!
  before_action :set_book

  def create
    @book.favorites.create(user_id: current_user.id)
  end

  def destroy
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :book_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	 before_action :authenticate_user!
def search
	@range = params[:range]
	search = params[:search]
	word = params[:word]

if  @range == '1'
	@user = User.search(search,word)
else
	@book = Book.search(search,word)
end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

def show
   @user = User.find(params[:id])
   @books = @user.books
   @book = Book.new
end

def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  if @book.save
    redirect_to book_path(@book), notice: "You have created book successfully."
  else
    @books = Book.all
    render 'index'
  end
end

def index
  @users = User.all
  @book = Book.new
  @user = current_user
end

def edit
  @user = User.find(params[:id])
  if current_user != @user
    redirect_to user_path(current_user)
  end
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to user_path(@user), notice: "You have updated user successfully."
  else
    render "edit"
  end
end

def follows
end

def followers
end

private
def user_params
  params.require(:user).permit(:name, :introduction, :profile_image, :postcode, :prefecture_code, :city, :street)
end

 def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

# def ensure_correct_user
#   @user = User.find(params[:id])
# unless @user == current_user
#   redirect_to user_path(current_user)
#  end
# end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to " login", new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

  <% if user_signed_in? %>
          <div class="search-form" style="text-align: center; margin-top: 70px;";>
               <%= form_tag(search_path, method: :get) do %>
                  <%= text_field_tag :word %>
                  <%= select_tag 'range', options_for_select([['User', '1'], ['Book', '2']]) %>
                  <%= select_tag 'search', options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                  <%= submit_tag "検索" %>
               <% end %>
          </div>
  <% end %>

    <div class="body">
      <div class="container">
        <p id="notice"><%= notice %></p>

            <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>